---
name: Tests
on:
    pull_request:
    push:
        branches: [master]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                aiida-core: [aiida-core==2.8.0, 'aiida-core>=2.8,<3']
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
            - run: pip install -e . pytest "${{ matrix.aiida-core }}"
            - run: python -m pytest -q
